Repository kpdecker/jsdiff, pull requests merged in 2023-12, with the labels that each got.

#393 Default value of line delimiters when a patch is applied (#228)
  src/patch/apply.js
  test/patch/apply.js
Labels: bugfix

#411 Fix a performance bug that leads to worse time complexity and cripplingly slow runtime in some cases
  src/diff/base.js
Labels: non-breaking-change, bugfix

#344 Option to strip trailing CR
  README.md
  src/diff/line.js
  test/diff/line.js
  test/patch/create.js
Labels: non-breaking-change

#439 Prefer to order deletions before insertions when the edit cost is the same, like the Myers diff paper does
  release-notes.md
  src/diff/base.js
  test/diff/array.js
  test/diff/line.js
  test/diff/word.js
Labels: breaking-change

#448 Speed up algorithm by not considering diagonals that take us off the edge of the graph
  README.md
  release-notes.md
  src/diff/base.js
Labels: non-breaking-change, performance
